// <auto-generated />
using System;
using CineWorld.Services.CommentAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CineWorld.Services.CommentAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241127145156_addCommentTableAndSeedData")]
    partial class addCommentTableAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CineWorld.Services.CommentAPI.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CommentParentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommentId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            Avatar = "https://cineworld-user-avatars.s3.amazonaws.com/users/4986f53c-a2db-4b71-80df-404bcad5413a/c7a45e1d-6b3b-4ef7-bd46-f28b32578dc1_bx170468-kD2X9O2XM9KH.jpg",
                            CommentContent = "This movie is amazing! I loved the characters and the plot.",
                            CreatedAt = new DateTime(2024, 11, 27, 21, 51, 55, 407, DateTimeKind.Local).AddTicks(3262),
                            FullName = "Admin",
                            MovieId = 1,
                            UserId = "4986f53c-a2db-4b71-80df-404bcad5413a"
                        },
                        new
                        {
                            CommentId = 2,
                            Avatar = "https://cineworld-user-avatars.s3.amazonaws.com/users/4986f53c-a2db-4b71-80df-404bcad5413a/c7a45e1d-6b3b-4ef7-bd46-f28b32578dc1_bx170468-kD2X9O2XM9KH.jpg",
                            CommentContent = "I agree, the movie was fantastic, especially the special effects!",
                            CommentParentId = 1,
                            CreatedAt = new DateTime(2024, 11, 27, 21, 51, 55, 407, DateTimeKind.Local).AddTicks(3275),
                            FullName = "Admin",
                            MovieId = 1,
                            UserId = "4986f53c-a2db-4b71-80df-404bcad5413a"
                        },
                        new
                        {
                            CommentId = 3,
                            Avatar = "https://cineworld-user-avatars.s3.amazonaws.com/users/4986f53c-a2db-4b71-80df-404bcad5413a/c7a45e1d-6b3b-4ef7-bd46-f28b32578dc1_bx170468-kD2X9O2XM9KH.jpg",
                            CommentContent = "Episode 1 had a slow start, but it picked up towards the end!",
                            CreatedAt = new DateTime(2024, 11, 27, 21, 51, 55, 407, DateTimeKind.Local).AddTicks(3277),
                            FullName = "Admin",
                            MovieId = 2,
                            UserId = "4986f53c-a2db-4b71-80df-404bcad5413a"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
