// <auto-generated />
using System;
using CineWorld.Services.CommentAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CineWorld.Services.CommentAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CineWorld.Services.CommentAPI.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("CommentContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CommentParentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommentId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            CommentContent = "This movie is amazing! I loved the characters and the plot.",
                            CreatedAt = new DateTime(2024, 11, 26, 16, 55, 10, 743, DateTimeKind.Local).AddTicks(9577),
                            MovieId = 1,
                            UserId = "4986f53c-a2db-4b71-80df-404bcad5413a"
                        },
                        new
                        {
                            CommentId = 2,
                            CommentContent = "I agree, the movie was fantastic, especially the special effects!",
                            CommentParentId = 1,
                            CreatedAt = new DateTime(2024, 11, 26, 16, 55, 10, 743, DateTimeKind.Local).AddTicks(9590),
                            MovieId = 1,
                            UserId = "4986f53c-a2db-4b71-80df-404bcad5413a"
                        },
                        new
                        {
                            CommentId = 3,
                            CommentContent = "Episode 1 had a slow start, but it picked up towards the end!",
                            CreatedAt = new DateTime(2024, 11, 26, 16, 55, 10, 743, DateTimeKind.Local).AddTicks(9591),
                            MovieId = 2,
                            UserId = "4986f53c-a2db-4b71-80df-404bcad5413a"
                        },
                        new
                        {
                            CommentId = 4,
                            CommentContent = "Totally agree, the ending was the best part!",
                            CommentParentId = 3,
                            CreatedAt = new DateTime(2024, 11, 26, 16, 55, 10, 743, DateTimeKind.Local).AddTicks(9592),
                            MovieId = 2,
                            UserId = "4986f53c-a2db-4b71-80df-404bcad5413a"
                        },
                        new
                        {
                            CommentId = 5,
                            CommentContent = "I didn't enjoy this movie as much as the previous ones. The pacing was off.",
                            CreatedAt = new DateTime(2024, 11, 26, 16, 55, 10, 743, DateTimeKind.Local).AddTicks(9593),
                            MovieId = 3,
                            UserId = "4986f53c-a2db-4b71-80df-404bcad5413a"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
