// <auto-generated />
using System;
using CineWorld.Services.CommentAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CineWorld.Services.CommentAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CineWorld.Services.CommentAPI.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("CommentContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CommentParentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommentId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            CommentContent = "This movie is amazing! I loved the characters and the plot.",
                            CreatedAt = new DateTime(2024, 11, 23, 14, 49, 58, 72, DateTimeKind.Local).AddTicks(9391),
                            MovieId = 1,
                            UserId = "3a5a3321-ebbe-49ac-b3aa-0466a2072515"
                        },
                        new
                        {
                            CommentId = 2,
                            CommentContent = "I agree, the movie was fantastic, especially the special effects!",
                            CommentParentId = 1,
                            CreatedAt = new DateTime(2024, 11, 23, 14, 49, 58, 72, DateTimeKind.Local).AddTicks(9412),
                            MovieId = 1,
                            UserId = "af4f152c-5cdd-4027-8024-28919b019a2e"
                        },
                        new
                        {
                            CommentId = 3,
                            CommentContent = "Episode 1 had a slow start, but it picked up towards the end!",
                            CreatedAt = new DateTime(2024, 11, 23, 14, 49, 58, 72, DateTimeKind.Local).AddTicks(9415),
                            EpisodeId = 1,
                            MovieId = 2,
                            UserId = "3a5a3321-ebbe-49ac-b3aa-0466a2072515"
                        },
                        new
                        {
                            CommentId = 4,
                            CommentContent = "Totally agree, the ending was the best part!",
                            CommentParentId = 3,
                            CreatedAt = new DateTime(2024, 11, 23, 14, 49, 58, 72, DateTimeKind.Local).AddTicks(9418),
                            EpisodeId = 1,
                            MovieId = 2,
                            UserId = "af4f152c-5cdd-4027-8024-28919b019a2e"
                        },
                        new
                        {
                            CommentId = 5,
                            CommentContent = "I didn't enjoy this movie as much as the previous ones. The pacing was off.",
                            CreatedAt = new DateTime(2024, 11, 23, 14, 49, 58, 72, DateTimeKind.Local).AddTicks(9421),
                            MovieId = 3,
                            UserId = "b736c9ed-4b4f-4f75-be82-186c25a69e4e"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
