version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "123qwe!@#"
      ACCEPT_EULA: "Y"
    ports:
      - "1400:1433"
    networks:
      - productnetwork
  
  cineworld.services.authapi:
    build:
      context: .
      dockerfile: CineWorld.Services.AuthAPI/Dockerfile
    ports:
      - "7000:7000"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:7000
    volumes:
      - ./HttpsCerf:/app/HttpsCerf
    networks:
      - productnetwork
    restart: on-failure

  cineworld.services.movieapi:
    build:
      context: .
      dockerfile: CineWorld.Services.MovieAPI/Dockerfile
    ports:
      - "7001:7001"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:7001
    volumes:
      - ./HttpsCerf:/app/HttpsCerf
    networks:
      - productnetwork
    restart: on-failure

  cineworld.services.membershipapi:
    build:
      context: .
      dockerfile: CineWorld.Services.MembershipAPI/Dockerfile
    ports:
      - "7002:7002"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:7002
    volumes:
      - ./HttpsCerf:/app/HttpsCerf
    networks:
      - productnetwork
    restart: on-failure

  cineworld.services.commentapi:
    build:
      context: .
      dockerfile: CineWorld.Services.CommentAPI/Dockerfile
    ports:
      - "7003:7003"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:7003
    volumes:
      - ./HttpsCerf:/app/HttpsCerf
    networks:
      - productnetwork
    restart: on-failure

  cineworld.services.historyapi:
    build:
      context: .
      dockerfile: CineWorld.Services.HistoryAPI/Dockerfile
    ports:
      - "7004:7004"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:7004
    volumes:
      - ./HttpsCerf:/app/HttpsCerf
    networks:
      - productnetwork
    restart: on-failure

  cineworld.services.reactionapi:
    build:
      context: .
      dockerfile: CineWorld.Services.ReactionAPI/Dockerfile
    ports:
      - "7005:7005"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:7005
    volumes:
      - ./HttpsCerf:/app/HttpsCerf
    networks:
      - productnetwork
    restart: on-failure

networks:
  productnetwork:
