// <auto-generated />
using System;
using CineWorld.Services.HistoryAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CineWorld.Services.HistoryAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CineWorld.Services.HistoryAPI.Models.WatchHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EpisodeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastWatched")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("WatchedDuration")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("watchHistories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EpisodeId = 2,
                            LastWatched = new DateTime(2024, 11, 1, 17, 30, 0, 0, DateTimeKind.Local),
                            UserId = "user123",
                            WatchedDuration = new TimeSpan(0, 0, 20, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            EpisodeId = 1,
                            LastWatched = new DateTime(2024, 11, 2, 18, 0, 0, 0, DateTimeKind.Local),
                            UserId = "user456",
                            WatchedDuration = new TimeSpan(0, 0, 15, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            EpisodeId = 3,
                            LastWatched = new DateTime(2024, 11, 3, 21, 45, 0, 0, DateTimeKind.Local),
                            UserId = "user789",
                            WatchedDuration = new TimeSpan(0, 0, 5, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            EpisodeId = 1,
                            LastWatched = new DateTime(2024, 11, 4, 23, 0, 0, 0, DateTimeKind.Local),
                            UserId = "user123",
                            WatchedDuration = new TimeSpan(0, 0, 30, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            EpisodeId = 2,
                            LastWatched = new DateTime(2024, 11, 6, 1, 15, 0, 0, DateTimeKind.Local),
                            UserId = "user456",
                            WatchedDuration = new TimeSpan(0, 0, 10, 0, 0)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
