// <auto-generated />
using System;
using CineWorld.Services.MovieAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CineWorld.Services.MovieAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241020175034_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CineWorld.Services.MovieAPI.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Phim Bộ",
                            Slug = "series",
                            Status = true
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Phim Lẻ",
                            Slug = "single",
                            Status = true
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "TV Shows",
                            Slug = "tvshows",
                            Status = true
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Hoạt Hình",
                            Slug = "hoathinh",
                            Status = true
                        });
                });

            modelBuilder.Entity("CineWorld.Services.MovieAPI.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("CountryId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasFilter("[Slug] IS NOT NULL");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            Name = "Trung Quốc",
                            Slug = "trung-quoc",
                            Status = true
                        },
                        new
                        {
                            CountryId = 2,
                            Name = "Hàn Quốc",
                            Slug = "han-quoc",
                            Status = true
                        },
                        new
                        {
                            CountryId = 3,
                            Name = "Nhật Bản",
                            Slug = "nhat-ban",
                            Status = true
                        },
                        new
                        {
                            CountryId = 4,
                            Name = "Thái Lan",
                            Slug = "thai-lan",
                            Status = true
                        },
                        new
                        {
                            CountryId = 5,
                            Name = "Âu Mỹ",
                            Slug = "au-my",
                            Status = true
                        },
                        new
                        {
                            CountryId = 6,
                            Name = "Đài Loan",
                            Slug = "dai-loan",
                            Status = true
                        },
                        new
                        {
                            CountryId = 7,
                            Name = "Hồng Kông",
                            Slug = "hong-kong",
                            Status = true
                        },
                        new
                        {
                            CountryId = 8,
                            Name = "Ấn Độ",
                            Slug = "an-do",
                            Status = true
                        },
                        new
                        {
                            CountryId = 9,
                            Name = "Anh",
                            Slug = "anh",
                            Status = true
                        },
                        new
                        {
                            CountryId = 10,
                            Name = "Pháp",
                            Slug = "phap",
                            Status = true
                        },
                        new
                        {
                            CountryId = 11,
                            Name = "Canada",
                            Slug = "canada",
                            Status = true
                        },
                        new
                        {
                            CountryId = 12,
                            Name = "Quốc Gia Khác",
                            Slug = "quoc-gia-khac",
                            Status = true
                        },
                        new
                        {
                            CountryId = 13,
                            Name = "Đức",
                            Slug = "duc",
                            Status = true
                        },
                        new
                        {
                            CountryId = 14,
                            Name = "Tây Ban Nha",
                            Slug = "tay-ban-nha",
                            Status = true
                        },
                        new
                        {
                            CountryId = 15,
                            Name = "Thổ Nhĩ Kỳ",
                            Slug = "tho-nhi-ky",
                            Status = true
                        },
                        new
                        {
                            CountryId = 16,
                            Name = "Hà Lan",
                            Slug = "ha-lan",
                            Status = true
                        },
                        new
                        {
                            CountryId = 17,
                            Name = "Indonesia",
                            Slug = "indonesia",
                            Status = true
                        },
                        new
                        {
                            CountryId = 18,
                            Name = "Nga",
                            Slug = "nga",
                            Status = true
                        },
                        new
                        {
                            CountryId = 19,
                            Name = "Mexico",
                            Slug = "mexico",
                            Status = true
                        },
                        new
                        {
                            CountryId = 20,
                            Name = "Ba Lan",
                            Slug = "ba-lan",
                            Status = true
                        },
                        new
                        {
                            CountryId = 21,
                            Name = "Úc",
                            Slug = "uc",
                            Status = true
                        },
                        new
                        {
                            CountryId = 22,
                            Name = "Thụy Điển",
                            Slug = "thuy-dien",
                            Status = true
                        },
                        new
                        {
                            CountryId = 23,
                            Name = "Malaysia",
                            Slug = "malaysia",
                            Status = true
                        },
                        new
                        {
                            CountryId = 24,
                            Name = "Brazil",
                            Slug = "brazil",
                            Status = true
                        },
                        new
                        {
                            CountryId = 25,
                            Name = "Philippines",
                            Slug = "philippines",
                            Status = true
                        },
                        new
                        {
                            CountryId = 26,
                            Name = "Bồ Đào Nha",
                            Slug = "bo-dao-nha",
                            Status = true
                        },
                        new
                        {
                            CountryId = 27,
                            Name = "Ý",
                            Slug = "y",
                            Status = true
                        },
                        new
                        {
                            CountryId = 28,
                            Name = "Đan Mạch",
                            Slug = "dan-mach",
                            Status = true
                        },
                        new
                        {
                            CountryId = 29,
                            Name = "UAE",
                            Slug = "uae",
                            Status = true
                        },
                        new
                        {
                            CountryId = 30,
                            Name = "Na Uy",
                            Slug = "na-uy",
                            Status = true
                        },
                        new
                        {
                            CountryId = 31,
                            Name = "Thụy Sĩ",
                            Slug = "thuy-si",
                            Status = true
                        },
                        new
                        {
                            CountryId = 32,
                            Name = "Châu Phi",
                            Slug = "chau-phi",
                            Status = true
                        },
                        new
                        {
                            CountryId = 33,
                            Name = "Nam Phi",
                            Slug = "nam-phi",
                            Status = true
                        },
                        new
                        {
                            CountryId = 34,
                            Name = "Ukraina",
                            Slug = "ukraina",
                            Status = true
                        },
                        new
                        {
                            CountryId = 35,
                            Name = "Ả Rập Xê Út",
                            Slug = "a-rap-xe-ut",
                            Status = true
                        });
                });

            modelBuilder.Entity("CineWorld.Services.MovieAPI.Models.Episode", b =>
                {
                    b.Property<int>("EpisodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EpisodeId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsFree")
                        .HasColumnType("bit");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EpisodeId");

                    b.HasIndex("MovieId", "EpisodeNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Movie_EpisodeNumber");

                    b.ToTable("Episodes");

                    b.HasData(
                        new
                        {
                            EpisodeId = 1,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 1,
                            IsFree = false,
                            MovieId = 1,
                            Name = "1",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 2,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 2,
                            IsFree = false,
                            MovieId = 1,
                            Name = "2",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 3,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 3,
                            IsFree = false,
                            MovieId = 1,
                            Name = "3",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 4,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 4,
                            IsFree = false,
                            MovieId = 1,
                            Name = "4",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 5,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 5,
                            IsFree = false,
                            MovieId = 1,
                            Name = "5",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 6,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 6,
                            IsFree = false,
                            MovieId = 1,
                            Name = "6",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 7,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 7,
                            IsFree = false,
                            MovieId = 1,
                            Name = "7",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 8,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 8,
                            IsFree = false,
                            MovieId = 1,
                            Name = "8",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 9,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 9,
                            IsFree = false,
                            MovieId = 1,
                            Name = "9",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 10,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 10,
                            IsFree = false,
                            MovieId = 1,
                            Name = "10",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 11,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 11,
                            IsFree = false,
                            MovieId = 1,
                            Name = "11",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 12,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 12,
                            IsFree = false,
                            MovieId = 1,
                            Name = "12",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 13,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 13,
                            IsFree = false,
                            MovieId = 1,
                            Name = "13",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 14,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 14,
                            IsFree = false,
                            MovieId = 1,
                            Name = "14",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 15,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 15,
                            IsFree = false,
                            MovieId = 1,
                            Name = "15",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 16,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 16,
                            IsFree = false,
                            MovieId = 1,
                            Name = "16",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 17,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 17,
                            IsFree = false,
                            MovieId = 1,
                            Name = "17",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 18,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 18,
                            IsFree = false,
                            MovieId = 1,
                            Name = "18",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 19,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 19,
                            IsFree = false,
                            MovieId = 1,
                            Name = "19",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 20,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 20,
                            IsFree = false,
                            MovieId = 1,
                            Name = "20",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 21,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 21,
                            IsFree = false,
                            MovieId = 1,
                            Name = "21",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 22,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 22,
                            IsFree = false,
                            MovieId = 1,
                            Name = "22",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 23,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 23,
                            IsFree = false,
                            MovieId = 1,
                            Name = "23",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 24,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 24,
                            IsFree = false,
                            MovieId = 1,
                            Name = "24",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 25,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 25,
                            IsFree = false,
                            MovieId = 1,
                            Name = "25",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 26,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 26,
                            IsFree = false,
                            MovieId = 1,
                            Name = "26",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 27,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 27,
                            IsFree = false,
                            MovieId = 1,
                            Name = "27",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 28,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 28,
                            IsFree = false,
                            MovieId = 1,
                            Name = "28",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 29,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 1,
                            IsFree = false,
                            MovieId = 2,
                            Name = "1",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 30,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 2,
                            IsFree = false,
                            MovieId = 2,
                            Name = "2",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 31,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 3,
                            IsFree = false,
                            MovieId = 2,
                            Name = "3",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 32,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 4,
                            IsFree = false,
                            MovieId = 2,
                            Name = "4",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 33,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 5,
                            IsFree = false,
                            MovieId = 2,
                            Name = "5",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 34,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 6,
                            IsFree = false,
                            MovieId = 2,
                            Name = "6",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 35,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 7,
                            IsFree = false,
                            MovieId = 2,
                            Name = "7",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 36,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 8,
                            IsFree = false,
                            MovieId = 2,
                            Name = "8",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 37,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 9,
                            IsFree = false,
                            MovieId = 2,
                            Name = "9",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        },
                        new
                        {
                            EpisodeId = 38,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc),
                            EpisodeNumber = 10,
                            IsFree = false,
                            MovieId = 2,
                            Name = "10",
                            Status = true,
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 6, 28, 583, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CineWorld.Services.MovieAPI.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("GenreId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasFilter("[Slug] IS NOT NULL");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            Name = "Hành Động",
                            Slug = "hanh-dong",
                            Status = true
                        },
                        new
                        {
                            GenreId = 2,
                            Name = "Tình Cảm",
                            Slug = "tinh-cam",
                            Status = true
                        },
                        new
                        {
                            GenreId = 3,
                            Name = "Hài Hước",
                            Slug = "hai-huoc",
                            Status = true
                        },
                        new
                        {
                            GenreId = 4,
                            Name = "Cổ Trang",
                            Slug = "co-trang",
                            Status = true
                        },
                        new
                        {
                            GenreId = 5,
                            Name = "Tâm Lý",
                            Slug = "tam-ly",
                            Status = true
                        },
                        new
                        {
                            GenreId = 6,
                            Name = "Hình Sự",
                            Slug = "hinh-su",
                            Status = true
                        },
                        new
                        {
                            GenreId = 7,
                            Name = "Chiến Tranh",
                            Slug = "chien-tranh",
                            Status = true
                        },
                        new
                        {
                            GenreId = 8,
                            Name = "Thể Thao",
                            Slug = "the-thao",
                            Status = true
                        },
                        new
                        {
                            GenreId = 9,
                            Name = "Võ Thuật",
                            Slug = "vo-thuat",
                            Status = true
                        },
                        new
                        {
                            GenreId = 10,
                            Name = "Viễn Tưởng",
                            Slug = "vien-tuong",
                            Status = true
                        },
                        new
                        {
                            GenreId = 11,
                            Name = "Phiêu Lưu",
                            Slug = "phieu-luu",
                            Status = true
                        },
                        new
                        {
                            GenreId = 12,
                            Name = "Khoa Học",
                            Slug = "khoa-hoc",
                            Status = true
                        },
                        new
                        {
                            GenreId = 13,
                            Name = "Kinh Dị",
                            Slug = "kinh-di",
                            Status = true
                        },
                        new
                        {
                            GenreId = 14,
                            Name = "Âm Nhạc",
                            Slug = "am-nhac",
                            Status = true
                        },
                        new
                        {
                            GenreId = 15,
                            Name = "Thần Thoại",
                            Slug = "than-thoai",
                            Status = true
                        },
                        new
                        {
                            GenreId = 16,
                            Name = "Tài Liệu",
                            Slug = "tai-lieu",
                            Status = true
                        },
                        new
                        {
                            GenreId = 17,
                            Name = "Gia Đình",
                            Slug = "gia-dinh",
                            Status = true
                        },
                        new
                        {
                            GenreId = 18,
                            Name = "Chính kịch",
                            Slug = "chinh-kich",
                            Status = true
                        },
                        new
                        {
                            GenreId = 19,
                            Name = "Bí ẩn",
                            Slug = "bi-an",
                            Status = true
                        },
                        new
                        {
                            GenreId = 20,
                            Name = "Học Đường",
                            Slug = "hoc-duong",
                            Status = true
                        },
                        new
                        {
                            GenreId = 21,
                            Name = "Kinh Điển",
                            Slug = "kinh-dien",
                            Status = true
                        },
                        new
                        {
                            GenreId = 22,
                            Name = "Phim 18+",
                            Slug = "phim-18",
                            Status = true
                        });
                });

            modelBuilder.Entity("CineWorld.Services.MovieAPI.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EpisodeCurrent")
                        .HasColumnType("int");

                    b.Property<int?>("EpisodeTotal")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHot")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Trailer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CountryId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            CategoryId = 4,
                            CountryId = 1,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 42, 0, 869, DateTimeKind.Utc),
                            Description = "Phﾆｰﾆ｡ng Hﾃ�n, thﾃ｢n sinh ra lﾃ� nﾃｴ b盻冂 c盻ｧa m盻冲 ﾄ黛ｺ｡i gia t盻冂. Khﾃｴng ch蘯･p nh蘯ｭn s盻� ph蘯ｭn c盻ｧa mﾃｬnh, h蘯ｯn h盻皇 lﾃｩn vﾃｵ cﾃｴng, sau ﾄ妥ｳ nh盻� m盻冲 ﾄ黛ｺ｡i k盻ｳ ng盻� mﾃ� d蘯･n thﾃ｢n vﾃ�o con ﾄ柁ｰ盻拵g tu tiﾃｪn ﾄ黛ｺｧy tr蘯ｯc tr盻�.",
                            Duration = "25 phﾃｺt/t蘯ｭp",
                            EpisodeCurrent = 28,
                            ImageUrl = "https://img.ophim.live/uploads/movies/vinh-sinh-phan-3-thumb.jpg",
                            IsHot = false,
                            Name = "Vﾄｩnh Sinh (Ph蘯ｧn 3)",
                            OriginName = "Immortality (Season 3)",
                            Slug = "vinh-sinh-phan-3",
                            Status = true,
                            Trailer = "https://www.youtube.com/watch?v=DjylTsonlSw",
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 42, 0, 869, DateTimeKind.Utc),
                            Year = 2024
                        },
                        new
                        {
                            MovieId = 2,
                            CategoryId = 1,
                            CountryId = 5,
                            CreatedDate = new DateTime(2024, 10, 20, 17, 42, 0, 869, DateTimeKind.Utc),
                            Description = "<p>M盻冲 thi蘯ｿu niﾃｪn b盻� b蘯ｯt n蘯｡t tham gia cﾃ｡c cu盻冂 thi s蘯ｯc ﾄ黛ｺｹp nhﾆｰ m盻冲 cﾃ｡ch ﾄ黛ｻ� tr蘯｣ thﾃｹ. Cﾃｴ ﾄ柁ｰ盻｣c m盻冲 hu蘯･n luy盻㌻ viﾃｪn tai ti蘯ｿng giﾃｺp ﾄ黛ｻ｡, ngﾆｰ盻拱 s盻嬶 nh蘯ｭn ra mﾃｬnh ﾄ疎ng sa l蘯ｧy.</p>",
                            Duration = "42phﾃｺt/t蘯ｭp",
                            EpisodeCurrent = 10,
                            EpisodeTotal = 10,
                            ImageUrl = "https://img.ophim.live/uploads/movies/vo-do-phan-2-thumb.jpg",
                            IsHot = false,
                            Name = "Vﾃｴ ﾄ黛ｻ� (Ph蘯ｧn 2)",
                            OriginName = "Insatiable (Season 2)",
                            Slug = "vo-do-phan-2",
                            Status = true,
                            Trailer = "",
                            UpdatedDate = new DateTime(2024, 10, 20, 17, 42, 0, 869, DateTimeKind.Utc),
                            Year = 2018
                        });
                });

            modelBuilder.Entity("CineWorld.Services.MovieAPI.Models.MovieGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieGenres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreId = 10,
                            MovieId = 1
                        },
                        new
                        {
                            Id = 2,
                            GenreId = 1,
                            MovieId = 1
                        },
                        new
                        {
                            Id = 3,
                            GenreId = 2,
                            MovieId = 2
                        },
                        new
                        {
                            Id = 4,
                            GenreId = 3,
                            MovieId = 2
                        },
                        new
                        {
                            Id = 5,
                            GenreId = 5,
                            MovieId = 2
                        });
                });

            modelBuilder.Entity("CineWorld.Services.MovieAPI.Models.Series", b =>
                {
                    b.Property<int>("SeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeriesId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("SeriesId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasFilter("[Slug] IS NOT NULL");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("CineWorld.Services.MovieAPI.Models.Server", b =>
                {
                    b.Property<int>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServerId"));

                    b.Property<int>("EpisodeId")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServerId");

                    b.HasIndex("EpisodeId");

                    b.ToTable("Servers");

                    b.HasData(
                        new
                        {
                            ServerId = 1,
                            EpisodeId = 1,
                            Link = "https://vip.opstream11.com/share/fab4fd725511924faa4daab64a353415",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 2,
                            EpisodeId = 2,
                            Link = "https://vip.opstream11.com/share/48d740cb434f20ec8b9dd4007e798eb4",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 3,
                            EpisodeId = 3,
                            Link = "https://vip.opstream11.com/share/10ccc3d6b30e89b173594526e81df7b9",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 4,
                            EpisodeId = 4,
                            Link = "https://vip.opstream11.com/share/9ae82c26134ecd4981bda3c252fc1acf",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 5,
                            EpisodeId = 5,
                            Link = "https://vip.opstream11.com/share/4580593c772e8cda49fcf7668a785ac4",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 6,
                            EpisodeId = 6,
                            Link = "https://vip.opstream11.com/share/7276c0c3f88b2a852674bd7e1cda0cf6",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 7,
                            EpisodeId = 7,
                            Link = "https://vip.opstream11.com/share/822b440edda4c46a5e1dad463eaf8ebd",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 8,
                            EpisodeId = 8,
                            Link = "https://vip.opstream11.com/share/3a74864c593d71aa5eec4da27f11768f",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 9,
                            EpisodeId = 9,
                            Link = "https://vip.opstream11.com/share/5fa3410e6fd97e1c2ed4eadfb7eff53f",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 10,
                            EpisodeId = 10,
                            Link = "https://vip.opstream11.com/share/90c9acf337005013884727424781ca24",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 11,
                            EpisodeId = 11,
                            Link = "https://vip.opstream11.com/share/57f3c6d49921c666e47139e2ead526e3",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 12,
                            EpisodeId = 12,
                            Link = "https://vip.opstream11.com/share/df5bb8067b7b1d641275af93581dea28",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 13,
                            EpisodeId = 13,
                            Link = "https://vip.opstream11.com/share/1a81daeb419a28fc7a373eb87bc3ef65",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 14,
                            EpisodeId = 14,
                            Link = "https://vip.opstream11.com/share/5beab85f16162a828932242cbfc52994",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 15,
                            EpisodeId = 15,
                            Link = "https://vip.opstream11.com/share/1dcfe838513ec134aa9cd68df4b08ff2",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 16,
                            EpisodeId = 16,
                            Link = "https://vip.opstream11.com/share/3e658cb2a57f417dc712210ba28c8f4c",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 17,
                            EpisodeId = 17,
                            Link = "https://vip.opstream11.com/share/e02cf150a0e8155a1bf54e4d586dcb37",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 18,
                            EpisodeId = 18,
                            Link = "https://vip.opstream11.com/share/838b5a042f1761ef0b5981585a0a7f38",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 19,
                            EpisodeId = 19,
                            Link = "https://vip.opstream11.com/share/2167afc4a46ea99c6b39b178f4c8501d",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 20,
                            EpisodeId = 20,
                            Link = "https://vip.opstream11.com/share/b1606b159abc283677c84d68e91ec97a",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 21,
                            EpisodeId = 21,
                            Link = "https://vip.opstream15.com/share/95938bd687b287423c514deeae8bf4f1",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 22,
                            EpisodeId = 22,
                            Link = "https://vip.opstream15.com/share/ba8cf349f278c2ae7f53ba026389fabd",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 23,
                            EpisodeId = 23,
                            Link = "https://vip.opstream15.com/share/a1d2a5b05d09395f32299a4d270a9a32",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 24,
                            EpisodeId = 24,
                            Link = "https://vip.opstream15.com/share/4ff82c0b528f93716115986da0412623",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 25,
                            EpisodeId = 25,
                            Link = "https://vip.opstream15.com/share/f45451d5c725bd5795d432e970d3d978",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 26,
                            EpisodeId = 26,
                            Link = "https://vip.opstream15.com/share/3ae04cd9569705cc18fd51df7e870279",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 27,
                            EpisodeId = 27,
                            Link = "https://vip.opstream15.com/share/9f2dab581c42e1381065d4d6dbd75d1a",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 28,
                            EpisodeId = 28,
                            Link = "https://vip.opstream15.com/share/063f5947bbefa2dc4936b33f80cab66c",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 29,
                            EpisodeId = 29,
                            Link = "https://vip.opstream16.com/share/ea159dc9788ffac311592613b7f71fbb",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 30,
                            EpisodeId = 30,
                            Link = "https://vip.opstream16.com/share/1a68e5f4ade56ed1d4bf273e55510750",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 31,
                            EpisodeId = 31,
                            Link = "https://vip.opstream16.com/share/99f59c0842e83c808dd1813b48a37c6a",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 32,
                            EpisodeId = 32,
                            Link = "https://vip.opstream16.com/share/8b4224068a41c5d37f5e2d54f3995089",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 33,
                            EpisodeId = 33,
                            Link = "https://vip.opstream16.com/share/d04863f100d59b3eb688a11f95b0ae60",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 34,
                            EpisodeId = 34,
                            Link = "https://vip.opstream16.com/share/063e26c670d07bb7c4d30e6fc69fe056",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 35,
                            EpisodeId = 35,
                            Link = "https://vip.opstream16.com/share/878d5691c824ee2aaf770f7d36c151d6",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 36,
                            EpisodeId = 36,
                            Link = "https://vip.opstream16.com/share/565030e1fce4e481f9823a7de3b8a047",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 37,
                            EpisodeId = 37,
                            Link = "https://vip.opstream16.com/share/bc7f621451b4f5df308a8e098112185d",
                            Name = "#1"
                        },
                        new
                        {
                            ServerId = 38,
                            EpisodeId = 38,
                            Link = "https://vip.opstream16.com/share/03cf87174debaccd689c90c34577b82f",
                            Name = "#1"
                        });
                });

            modelBuilder.Entity("CineWorld.Services.MovieAPI.Models.Episode", b =>
                {
                    b.HasOne("CineWorld.Services.MovieAPI.Models.Movie", "Movie")
                        .WithMany("Episodes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CineWorld.Services.MovieAPI.Models.Movie", b =>
                {
                    b.HasOne("CineWorld.Services.MovieAPI.Models.Category", "Category")
                        .WithMany("Movies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CineWorld.Services.MovieAPI.Models.Country", "Country")
                        .WithMany("Movies")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CineWorld.Services.MovieAPI.Models.Series", "Series")
                        .WithMany("Movies")
                        .HasForeignKey("SeriesId");

                    b.Navigation("Category");

                    b.Navigation("Country");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("CineWorld.Services.MovieAPI.Models.MovieGenre", b =>
                {
                    b.HasOne("CineWorld.Services.MovieAPI.Models.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CineWorld.Services.MovieAPI.Models.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CineWorld.Services.MovieAPI.Models.Server", b =>
                {
                    b.HasOne("CineWorld.Services.MovieAPI.Models.Episode", "Episode")
                        .WithMany("Servers")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Episode");
                });

            modelBuilder.Entity("CineWorld.Services.MovieAPI.Models.Category", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("CineWorld.Services.MovieAPI.Models.Country", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("CineWorld.Services.MovieAPI.Models.Episode", b =>
                {
                    b.Navigation("Servers");
                });

            modelBuilder.Entity("CineWorld.Services.MovieAPI.Models.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("CineWorld.Services.MovieAPI.Models.Movie", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("CineWorld.Services.MovieAPI.Models.Series", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
